openapi: 3.0.3
info:
  title: File Service API
  description: File Service API to check every 10 minutes folder and store data in Mongo DB
  version: "1.0"
servers:
  - url: http://localhost:8082/api/v1
paths:
  /count:
    get:
      summary: Check how many files are stored in Mongo DB collection currently
      description: Check how many files are stored in Mongo DB collection currently
      operationId: countFiles
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: integer
                format: int64
  /health:
    get:
      summary: Check if service is alive
      description: Check if service is alive
      operationId: health
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
